apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJhZGV3YWxlMDEuamZyb2cuaW8iOiB7CgkJCSJhdXRoIjogIlpHOWphMlZ5WTNKbFpEcElaV2x5WlhOelFERT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson